### ISSUE TITLE
Test on Matt's computer

### ISSUE THREAD

**Issue by dellaert** [borglab/gtsam-project-matlab#1]
@mksoccer please create a project based on this template and create issues if you encounter any problems (or a PR with updated documentation, if you see it is currently wrong). Please work with @varunagrawal and @ProfFan to resolve those issues and review your PRs.

**Comment by mattking-smith** [comment]
Where is MatlabWrap found? I am having trouble implementing this template given that I am getting the following output with cmake:
`
cmake ..
-- pybind11 v2.6.0 dev1
CMake Error at CMakeLists.txt:44 (include):
  include could not find load file:

    MatlabWrap


-- GTSAM include directory:  /usr/local/lib/cmake/GTSAM/../../../include
========== Configuration Options ==========
-- Project:                  example_matlab
-- MATLAB Root:              /usr/local/MATLAB/R2020b
-- Mex Compiler:             /usr/local/MATLAB/R2020b/bin/glnxa64/mex
===========================================
CMake Error at CMakeLists.txt:91 (matlab_wrap):
  Unknown CMake command "matlab_wrap".


-- Configuring incomplete, errors occurred!`

**Comment by varunagrawal** [comment]
You need to install the [wrap](https://github.com/borglab/wrap) project first.

**Comment by varunagrawal** [comment]
I should add that to the README, good catch.

**Comment by mattking-smith** [comment]
I thought I had the wrap project installed first, but I guess I do not...

**Comment by dellaert** [comment]
I thought you could do it with the wrap *inside* GTSAM?? We should allow for that, as that will be the 99% use case.

**Comment by mattking-smith** [comment]
I currently do have wrap inside of GTSAM, which is why I don't understand why its not recognized.

**Comment by varunagrawal** [comment]
Depends on how you've installed GTSAM. If you've done some custom path stuff, you need to update your PATH and other variables so that CMake can find it.

**Comment by dellaert** [comment]
I found that I needed to tell cmake to install the new project in the same path (for me `/Users/dellaert`) and then things work.

I recommend *never* to install in default /usr/local. It hides a bunch of issues our users will experience if they have no root access.

**Comment by varunagrawal** [comment]
^^ yep precisely what I meant by updating the paths. The CI is configured to use a local path so I don't believe this would be a problem.

**Comment by mattking-smith** [comment]
I think I have installed GTSAM is a very crude manner and am not sure I have the paths correctly established. I just had to download wrap and install again in order to get it to register the matlab toolbox. 

I am now getting the following error:
cmake ..
-- pybind11 v2.6.0 dev1
-- GTSAM include directory:  /usr/local/lib/cmake/GTSAM/../../../include
========== Configuration Options ==========
-- Project:                  example_matlab
-- MATLAB Root:              /usr/local/MATLAB/R2020b
-- Mex Compiler:             /usr/local/MATLAB/R2020b/bin/glnxa64/mex
===========================================
-- Building wrap module example
-- Installing Matlab Toolbox to /usr/local/gtsam_toolbox
-- Configuring done
CMake Error at /usr/local/lib/cmake/gtwrap/MatlabWrap.cmake:251 (add_library):
  Cannot find source file:

    target_sources-NOTFOUND

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  /usr/local/lib/cmake/gtwrap/MatlabWrap.cmake:79 (wrap_library_internal)
  /usr/local/lib/cmake/gtwrap/MatlabWrap.cmake:57 (wrap_and_install_library)
  CMakeLists.txt:91 (matlab_wrap)


CMake Error at /usr/local/lib/cmake/gtwrap/MatlabWrap.cmake:251 (add_library):
  No SOURCES given to target: example_matlab_wrapper
Call Stack (most recent call first):
  /usr/local/lib/cmake/gtwrap/MatlabWrap.cmake:79 (wrap_library_internal)
  /usr/local/lib/cmake/gtwrap/MatlabWrap.cmake:57 (wrap_and_install_library)
  CMakeLists.txt:91 (matlab_wrap)


CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by mattking-smith** [comment]
So I had to remove the build folder and recreate it, but now I am getting stuck with the following error at the sudo make -j8 step:

make -j8
Scanning dependencies of target example_matlab
[ 11%] Building CXX object CMakeFiles/example_matlab.dir/example/PrintExamples.cpp.o
[ 22%] Linking CXX shared library libexample_matlab.so
[ 22%] Built target example_matlab
[ 33%] Generating wrap/example/example_wrapper.cpp
Scanning dependencies of target SayGoodbye
Scanning dependencies of target SayHello
[ 55%] Building CXX object CMakeFiles/SayHello.dir/SayHello.cpp.o
[ 55%] Building CXX object CMakeFiles/SayGoodbye.dir/SayGoodbye.cpp.o
Ignoring classes: []
 
any suggestions?

**Comment by mattking-smith** [comment]
> So I had to remove the build folder and recreate it, but now I am getting stuck with the following error at the sudo make -j8 step:
> 
> make -j8
> Scanning dependencies of target example_matlab
> [ 11%] Building CXX object CMakeFiles/example_matlab.dir/example/PrintExamples.cpp.o
> [ 22%] Linking CXX shared library libexample_matlab.so
> [ 22%] Built target example_matlab
> [ 33%] Generating wrap/example/example_wrapper.cpp
> Scanning dependencies of target SayGoodbye
> Scanning dependencies of target SayHello
> [ 55%] Building CXX object CMakeFiles/SayHello.dir/SayHello.cpp.o
> [ 55%] Building CXX object CMakeFiles/SayGoodbye.dir/SayGoodbye.cpp.o
> Ignoring classes: []
> 
> any suggestions?

Is this a linking issue here?

**Comment by varunagrawal** [comment]
I wonder if this is because of linking with GTSAM. I would have to take a closer look to figure this out. I can get on a call later tonight (after 10 pm) or tomorrow.

**Comment by mattking-smith** [comment]
Yeah, I just managed to get past that error by directly editing the CMakeLists.txt such that I made this change: 
`#target_link_libraries(${CONVENIENCE_LIB_NAME} gtsam)
target_link_libraries(${CONVENIENCE_LIB_NAME} /home/matt/Documents/gtsam-project-matlab/build)'.

Now, I am getting the following error: 
`make -j8
-- pybind11 v2.6.0 dev1
-- GTSAM include directory:  /usr/local/lib/cmake/GTSAM/../../../include
========== Configuration Options ==========
-- Project:                  example_matlab
-- MATLAB Root:              /usr/local/MATLAB/R2020b
-- Mex Compiler:             /usr/local/MATLAB/R2020b/bin/glnxa64/mex
===========================================
-- Building wrap module example
-- Installing Matlab Toolbox to /usr/local/gtsam_toolbox
-- Configuring done
WARNING: Target "example_matlab_wrapper" requests linking to directory "/home/matt/Documents/gtsam-project-matlab/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "example_matlab_wrapper" requests linking to directory "/home/matt/Documents/gtsam-project-matlab/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "testExample" requests linking to directory "/home/matt/Documents/gtsam-project-matlab/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "SayGoodbye" requests linking to directory "/home/matt/Documents/gtsam-project-matlab/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "example_matlab" requests linking to directory "/home/matt/Documents/gtsam-project-matlab/build".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "SayHello" requests linking to directory "/home/matt/Documents/gtsam-project-matlab/build".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /home/matt/Documents/gtsam-project-matlab/build
[ 33%] Linking CXX shared library libexample_matlab.so
[ 33%] Built target example_matlab
[ 33%] Generating wrap/example/example_wrapper.cpp
Scanning dependencies of target SayHello
Scanning dependencies of target SayGoodbye
[ 33%] Building CXX object CMakeFiles/SayGoodbye.dir/SayGoodbye.cpp.o
[ 33%] Building CXX object CMakeFiles/SayHello.dir/SayHello.cpp.o
Ignoring classes: []
Scanning dependencies of target example_matlab_wrapper
[ 33%] Building CXX object CMakeFiles/example_matlab_wrapper.dir/wrap/example/example_wrapper.cpp.o
In file included from /usr/local/include/gtwrap/matlab.h:25,
                 from /home/matt/Documents/gtsam-project-matlab/build/wrap/example/example_wrapper.cpp:1:
/usr/local/include/gtsam/base/Vector.h:29:10: fatal error: Eigen/Core: No such file or directory
   29 | #include <Eigen/Core>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/example_matlab_wrapper.dir/build.make:68: CMakeFiles/example_matlab_wrapper.dir/wrap/example/example_wrapper.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:141: CMakeFiles/example_matlab_wrapper.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 33%] Linking CXX executable SayHello
[ 33%] Linking CXX executable SayGoodbye
[ 33%] Built target SayHello
[ 33%] Built target SayGoodbye
make: *** [Makefile:141: all] Error 2
`
which is no good either.

**Comment by varunagrawal** [comment]
That's because of the above hack. I highly recommend getting the GTSAM install working properly (even if it means installing to /usr/local/lib), that way everything should flow nicely.

**Comment by mattking-smith** [comment]
How would I know if it is or is not properly installed in /usr/local/lib? It appears I have all the proper files in that location, but is their another way to verify?

**Comment by mattking-smith** [comment]
Regardless, I am down for a call tonight to revolve this to make sure I have the correct installation location, and procedure

**Comment by varunagrawal** [comment]
I'll message you once I get back.

**Comment by mattking-smith** [comment]
> I'll message you once I get back.

Sounds good.
